@Library('Shared') _
pipeline {
    agent { label 'akbagent' }

    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace cleanup") {
            steps {
                script {
                    cleanWs()
                }
            }
        }

        stage('Git: Code Checkout') {
            steps {
                script {
                    code_checkout("git@github.com:Athithiyan0511/Jenkins-end2ned.git", "main")
                }
            }
        }

        stage('Verify: Docker Image Tags') {
            steps {
                script {
                    echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                    echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                }
            }
        }

        stage("Update: Kubernetes manifests") {
            steps {
                script {
                    dir('kubernetes') {
                        sh """
                            sed -i -e 's|image: .*|image: aadhi11m/wanderlust-backend-beta:${params.BACKEND_DOCKER_TAG}|g' backend.yaml
                            sed -i -e 's|image: .*|image: aadhi11m/wanderlust-frontend-beta:${params.FRONTEND_DOCKER_TAG}|g' frontend.yaml
                        """
                    }
                }
            }
        }

        stage("Git: Code update and push to GitHub") {
            steps {
                script {
                    withCredentials([gitUsernamePassword(credentialsId: 'github-cred', gitToolName: 'Default')]) {
                        sh '''
                            echo "Checking repository status:"
                            git status

                            echo "Adding changes to git:"
                            git add .

                            echo "Committing changes:"
                            git commit -m "Update Kubernetes image tags"

                            echo "Pushing changes to GitHub:"
                            git push git@github.com:Athithiyan0511/Jenkins-end2ned.git main
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            script {
                emailext attachLog: true,
                    from: 'athithiyan11@gmail.com',
                    subject: "Wanderlust Application has been updated and deployed - '${currentBuild.result}'",
                    body: """
                        <html>
                        <body>
                            <div>
                                <p><b>Project: ${env.JOB_NAME}</b></p>
                            </div>
                            <div>
                                <p><b>Build Number: ${env.BUILD_NUMBER}</b></p>
                            </div>
                            <div>
                                <p><b>URL: ${env.BUILD_URL}</b></p>
                            </div>
                        </body>
                        </html>
                    """,
                    to: 'athithiyan11@gmail.com',
                    mimeType: 'text/html'
            }
        }

        failure {
            script {
                emailext attachLog: true,
                    from: 'athithiyan11@gmail.com',
                    subject: "Wanderlust Application build failed - '${currentBuild.result}'",
                    body: """
                        <html>
                        <body>
                            <div>
                                <p><b>Project: ${env.JOB_NAME}</b></p>
                            </div>
                            <div>
                                <p><b>Build Number: ${env.BUILD_NUMBER}</b></p>
                            </div>
                        </body>
                        </html>
                    """,
                    to: 'athithiyan11@gmail.com',
                    mimeType: 'text/html'
            }
        }
    }
}